apiVersion: batch/v1
kind: CronJob
metadata:
  name: cron-custodian
spec:
  schedule: "*/5 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: cron-job-cc
            image: public.ecr.aws/f6z5e0l4/uat-cloud-custodian
            imagePullPolicy: Always
            env:
            - name: AWS_DEFAULT_REGION
              value: "us-east-1"
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: aws-credentials
                  key: AWS_ACCESS_KEY_ID
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: aws-credentials
                  key: AWS_SECRET_ACCESS_KEY    
            command:
            args: ["run","-v","-s","/opt/test","/opt/test/policy.yml"]    
          restartPolicy: OnFailure
